# Generated by Django 2.1.1 on 2019-05-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_journal',
            name='photo',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
